cmake_minimum_required(VERSION 3.16)

project(Tekst LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(
    tekst
    src/main.cpp
    src/lexer.cpp
    src/parser.cpp
    src/codegen.cpp
    src/ast.cpp
    src/builtins.cpp
    src/class.cpp
    src/environment.cpp
    src/errors.cpp
    src/file_io.cpp
    src/function.cpp
    src/repl.cpp
    src/value.cpp
)

add_executable(tk tk/tk.cpp)

target_include_directories(tekst PRIVATE src)

add_custom_command(TARGET tekst POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
            ${CMAKE_CURRENT_SOURCE_DIR}/src/runtime.cpp
            $<TARGET_FILE_DIR:tekst>/runtime.cpp
)

add_custom_command(TARGET tekst POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
            ${CMAKE_CURRENT_SOURCE_DIR}/src/runtime.h
            $<TARGET_FILE_DIR:tekst>/runtime.h
)

install(TARGETS tekst RUNTIME DESTINATION bin)

install(
    FILES
        src/runtime.cpp
        src/runtime.h
    DESTINATION bin
)